import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import { Toaster } from "@/components/ui/sonner/sonner";
import { SideNavigation, MobileDrawer } from "@/components/common";
import "@/styles/globals.css";
import "@/styles/main.scss";

const NOTO_SANS_KR = Noto_Sans_KR({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "shadcn UI - TODO List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={NOTO_SANS_KR.className}>
        <div className="h-screen w-full flex flex-1 flex-col lg:flex-row text-white">
          {/* 📱 모바일 Drawer (Client Component) */}
          <MobileDrawer />

          {/* 💻 데스크탑용 사이드바 */}
          <aside className="flex-1 h-full hidden lg:block w-[300px] shrink-0 ">
            <SideNavigation />
          </aside>

          {/* 🌿 메인 */}
          <main className=" w-full sm:p-6 md:p-8 text-zinc-800">
            {children}
          </main>
        </div>

        <Toaster />
      </body>
    </html>
  );
}
