import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";

// ======================
// 🧱 Components
// ======================
import { Toaster } from "@/components/ui/sonner/sonner";
import { SideNavigation, MobileDrawer } from "@/components/common";

// ======================
// 🎨 Styles
// ======================
import "@/styles/globals.css";
import "@/styles/main.scss";

// ======================
// 🪶 Font
// ======================
const NOTO_SANS_KR = Noto_Sans_KR({ subsets: ["latin"] });

// ======================
// 🌍 Metadata
// ======================
export const metadata: Metadata = {
  title: "shadcn UI - TODO List",
  description: "Generated by create next app",
};

// ======================
// 🧩 RootLayout Component
// ======================
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={NOTO_SANS_KR.className}>
        <div className="flex h-screen w-full flex-col lg:flex-row text-white">
          {/* 모바일 내비게이션 */}
          <MobileDrawer />

          {/* 사이드바 (데스크탑 전용) */}
          <aside className="hidden h-full w-[300px] shrink-0 lg:block">
            <SideNavigation />
          </aside>

          {/* 메인 콘텐츠 */}
          <main className="w-full sm:p-6 md:p-8 text-zinc-800">{children}</main>
        </div>

        {/* 전역 알림 */}
        <Toaster />
      </body>
    </html>
  );
}
